apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "deepdive-quarkus.fullname" . }}
  labels:
    {{- include "deepdive-quarkus.labels" . | nindent 4 }}
spec:
  host: {{ .Values.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "deepdive-quarkus.fullname" . }}
    weight: 100
  wildcardPolicy: None